server:
  port: 8897
spring:
  rabbitmq:
    host: 47.102.218.26
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动确认消息
#    com.kxj.listener:
#      simple:
#        acknowledge-mode: manual