server:
  port: 8902
logging:
  level:
    root: info
  # logging.path和logging.file只会生效一个
  path: D:/github/SpringBoot-Learning/Scheduler/src/main/resources
  # 默认的文件名是：spring.log
#  file: my.log
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xuecloud?tinyInt1isBit=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none