server:
  port: 8894
spring:
  rabbitmq:
    host: 47.102.218.26
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual